# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uicameras.ui'
#
# Created: Fri Jan 09 16:09:30 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CamDialog(object):
    def setupUi(self, CamDialog):
        CamDialog.setObjectName(_fromUtf8("CamDialog"))
        CamDialog.resize(259, 359)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Camera-video.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CamDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(CamDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(CamDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkCam1 = QtGui.QCheckBox(self.groupBox)
        self.chkCam1.setText(_fromUtf8(""))
        self.chkCam1.setObjectName(_fromUtf8("chkCam1"))
        self.gridLayout.addWidget(self.chkCam1, 0, 0, 1, 1)
        self.pbCam1 = QtGui.QPushButton(self.groupBox)
        self.pbCam1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam1.sizePolicy().hasHeightForWidth())
        self.pbCam1.setSizePolicy(sizePolicy)
        self.pbCam1.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam1.setFont(font)
        self.pbCam1.setObjectName(_fromUtf8("pbCam1"))
        self.gridLayout.addWidget(self.pbCam1, 0, 1, 1, 1)
        self.txtDesc1 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc1.setFont(font)
        self.txtDesc1.setObjectName(_fromUtf8("txtDesc1"))
        self.gridLayout.addWidget(self.txtDesc1, 0, 2, 1, 1)
        self.chkCam2 = QtGui.QCheckBox(self.groupBox)
        self.chkCam2.setText(_fromUtf8(""))
        self.chkCam2.setObjectName(_fromUtf8("chkCam2"))
        self.gridLayout.addWidget(self.chkCam2, 1, 0, 1, 1)
        self.pbCam2 = QtGui.QPushButton(self.groupBox)
        self.pbCam2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam2.sizePolicy().hasHeightForWidth())
        self.pbCam2.setSizePolicy(sizePolicy)
        self.pbCam2.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam2.setFont(font)
        self.pbCam2.setObjectName(_fromUtf8("pbCam2"))
        self.gridLayout.addWidget(self.pbCam2, 1, 1, 1, 1)
        self.txtDesc2 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc2.setFont(font)
        self.txtDesc2.setObjectName(_fromUtf8("txtDesc2"))
        self.gridLayout.addWidget(self.txtDesc2, 1, 2, 1, 1)
        self.chkCam3 = QtGui.QCheckBox(self.groupBox)
        self.chkCam3.setText(_fromUtf8(""))
        self.chkCam3.setObjectName(_fromUtf8("chkCam3"))
        self.gridLayout.addWidget(self.chkCam3, 2, 0, 1, 1)
        self.pbCam3 = QtGui.QPushButton(self.groupBox)
        self.pbCam3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam3.sizePolicy().hasHeightForWidth())
        self.pbCam3.setSizePolicy(sizePolicy)
        self.pbCam3.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam3.setFont(font)
        self.pbCam3.setObjectName(_fromUtf8("pbCam3"))
        self.gridLayout.addWidget(self.pbCam3, 2, 1, 1, 1)
        self.txtDesc3 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc3.setFont(font)
        self.txtDesc3.setObjectName(_fromUtf8("txtDesc3"))
        self.gridLayout.addWidget(self.txtDesc3, 2, 2, 1, 1)
        self.chkCam4 = QtGui.QCheckBox(self.groupBox)
        self.chkCam4.setText(_fromUtf8(""))
        self.chkCam4.setObjectName(_fromUtf8("chkCam4"))
        self.gridLayout.addWidget(self.chkCam4, 3, 0, 1, 1)
        self.pbCam4 = QtGui.QPushButton(self.groupBox)
        self.pbCam4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam4.sizePolicy().hasHeightForWidth())
        self.pbCam4.setSizePolicy(sizePolicy)
        self.pbCam4.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam4.setFont(font)
        self.pbCam4.setObjectName(_fromUtf8("pbCam4"))
        self.gridLayout.addWidget(self.pbCam4, 3, 1, 1, 1)
        self.txtDesc4 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc4.setFont(font)
        self.txtDesc4.setObjectName(_fromUtf8("txtDesc4"))
        self.gridLayout.addWidget(self.txtDesc4, 3, 2, 1, 1)
        self.chkCam5 = QtGui.QCheckBox(self.groupBox)
        self.chkCam5.setText(_fromUtf8(""))
        self.chkCam5.setObjectName(_fromUtf8("chkCam5"))
        self.gridLayout.addWidget(self.chkCam5, 4, 0, 1, 1)
        self.pbCam5 = QtGui.QPushButton(self.groupBox)
        self.pbCam5.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam5.sizePolicy().hasHeightForWidth())
        self.pbCam5.setSizePolicy(sizePolicy)
        self.pbCam5.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam5.setFont(font)
        self.pbCam5.setObjectName(_fromUtf8("pbCam5"))
        self.gridLayout.addWidget(self.pbCam5, 4, 1, 1, 1)
        self.txtDesc5 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc5.setFont(font)
        self.txtDesc5.setObjectName(_fromUtf8("txtDesc5"))
        self.gridLayout.addWidget(self.txtDesc5, 4, 2, 1, 1)
        self.chkCam6 = QtGui.QCheckBox(self.groupBox)
        self.chkCam6.setText(_fromUtf8(""))
        self.chkCam6.setObjectName(_fromUtf8("chkCam6"))
        self.gridLayout.addWidget(self.chkCam6, 5, 0, 1, 1)
        self.pbCam6 = QtGui.QPushButton(self.groupBox)
        self.pbCam6.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam6.sizePolicy().hasHeightForWidth())
        self.pbCam6.setSizePolicy(sizePolicy)
        self.pbCam6.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam6.setFont(font)
        self.pbCam6.setObjectName(_fromUtf8("pbCam6"))
        self.gridLayout.addWidget(self.pbCam6, 5, 1, 1, 1)
        self.txtDesc6 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc6.setFont(font)
        self.txtDesc6.setObjectName(_fromUtf8("txtDesc6"))
        self.gridLayout.addWidget(self.txtDesc6, 5, 2, 1, 1)
        self.chkCam7 = QtGui.QCheckBox(self.groupBox)
        self.chkCam7.setText(_fromUtf8(""))
        self.chkCam7.setObjectName(_fromUtf8("chkCam7"))
        self.gridLayout.addWidget(self.chkCam7, 6, 0, 1, 1)
        self.pbCam7 = QtGui.QPushButton(self.groupBox)
        self.pbCam7.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam7.sizePolicy().hasHeightForWidth())
        self.pbCam7.setSizePolicy(sizePolicy)
        self.pbCam7.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam7.setFont(font)
        self.pbCam7.setObjectName(_fromUtf8("pbCam7"))
        self.gridLayout.addWidget(self.pbCam7, 6, 1, 1, 1)
        self.txtDesc7 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc7.setFont(font)
        self.txtDesc7.setObjectName(_fromUtf8("txtDesc7"))
        self.gridLayout.addWidget(self.txtDesc7, 6, 2, 1, 1)
        self.chkCam8 = QtGui.QCheckBox(self.groupBox)
        self.chkCam8.setText(_fromUtf8(""))
        self.chkCam8.setObjectName(_fromUtf8("chkCam8"))
        self.gridLayout.addWidget(self.chkCam8, 7, 0, 1, 1)
        self.pbCam8 = QtGui.QPushButton(self.groupBox)
        self.pbCam8.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam8.sizePolicy().hasHeightForWidth())
        self.pbCam8.setSizePolicy(sizePolicy)
        self.pbCam8.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam8.setFont(font)
        self.pbCam8.setObjectName(_fromUtf8("pbCam8"))
        self.gridLayout.addWidget(self.pbCam8, 7, 1, 1, 1)
        self.txtDesc8 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc8.setFont(font)
        self.txtDesc8.setObjectName(_fromUtf8("txtDesc8"))
        self.gridLayout.addWidget(self.txtDesc8, 7, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(CamDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CamDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CamDialog.close)
        QtCore.QObject.connect(self.chkCam1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam1.setEnabled)
        QtCore.QObject.connect(self.chkCam2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam2.setEnabled)
        QtCore.QObject.connect(self.chkCam3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam3.setEnabled)
        QtCore.QObject.connect(self.chkCam4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam4.setEnabled)
        QtCore.QObject.connect(self.chkCam5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam5.setEnabled)
        QtCore.QObject.connect(self.chkCam6, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam6.setEnabled)
        QtCore.QObject.connect(self.chkCam7, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam7.setEnabled)
        QtCore.QObject.connect(self.chkCam8, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam8.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CamDialog)

    def retranslateUi(self, CamDialog):
        CamDialog.setWindowTitle(_translate("CamDialog", "SSM Cameras", None))
        self.groupBox.setTitle(_translate("CamDialog", "Cameras", None))
        self.pbCam1.setText(_translate("CamDialog", "1", None))
        self.txtDesc1.setText(_translate("CamDialog", "Description", None))
        self.pbCam2.setText(_translate("CamDialog", "2", None))
        self.txtDesc2.setText(_translate("CamDialog", "Description", None))
        self.pbCam3.setText(_translate("CamDialog", "3", None))
        self.txtDesc3.setText(_translate("CamDialog", "Description", None))
        self.pbCam4.setText(_translate("CamDialog", "4", None))
        self.txtDesc4.setText(_translate("CamDialog", "Description", None))
        self.pbCam5.setText(_translate("CamDialog", "5", None))
        self.txtDesc5.setText(_translate("CamDialog", "Description", None))
        self.pbCam6.setText(_translate("CamDialog", "6", None))
        self.txtDesc6.setText(_translate("CamDialog", "Description", None))
        self.pbCam7.setText(_translate("CamDialog", "7", None))
        self.txtDesc7.setText(_translate("CamDialog", "Description", None))
        self.pbCam8.setText(_translate("CamDialog", "8", None))
        self.txtDesc8.setText(_translate("CamDialog", "Description", None))

