# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uicameras.ui'
#
# Created: Thu Feb 19 23:18:48 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CamDialog(object):
    def setupUi(self, CamDialog):
        CamDialog.setObjectName(_fromUtf8("CamDialog"))
        CamDialog.resize(468, 239)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Camera-video.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CamDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(CamDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(CamDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkCam1 = QtGui.QCheckBox(self.groupBox)
        self.chkCam1.setText(_fromUtf8(""))
        self.chkCam1.setObjectName(_fromUtf8("chkCam1"))
        self.gridLayout.addWidget(self.chkCam1, 0, 0, 1, 1)
        self.chkCam2 = QtGui.QCheckBox(self.groupBox)
        self.chkCam2.setText(_fromUtf8(""))
        self.chkCam2.setObjectName(_fromUtf8("chkCam2"))
        self.gridLayout.addWidget(self.chkCam2, 1, 0, 1, 1)
        self.txtDesc1 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc1.setFont(font)
        self.txtDesc1.setObjectName(_fromUtf8("txtDesc1"))
        self.gridLayout.addWidget(self.txtDesc1, 0, 2, 1, 1)
        self.pbRecord1 = QtGui.QPushButton(self.groupBox)
        self.pbRecord1.setEnabled(False)
        self.pbRecord1.setCheckable(True)
        self.pbRecord1.setChecked(False)
        self.pbRecord1.setObjectName(_fromUtf8("pbRecord1"))
        self.gridLayout.addWidget(self.pbRecord1, 0, 3, 1, 1)
        self.pbCam1 = QtGui.QPushButton(self.groupBox)
        self.pbCam1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam1.sizePolicy().hasHeightForWidth())
        self.pbCam1.setSizePolicy(sizePolicy)
        self.pbCam1.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam1.setFont(font)
        self.pbCam1.setCheckable(True)
        self.pbCam1.setObjectName(_fromUtf8("pbCam1"))
        self.gridLayout.addWidget(self.pbCam1, 0, 1, 1, 1)
        self.pbCam2 = QtGui.QPushButton(self.groupBox)
        self.pbCam2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam2.sizePolicy().hasHeightForWidth())
        self.pbCam2.setSizePolicy(sizePolicy)
        self.pbCam2.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam2.setFont(font)
        self.pbCam2.setCheckable(True)
        self.pbCam2.setObjectName(_fromUtf8("pbCam2"))
        self.gridLayout.addWidget(self.pbCam2, 1, 1, 1, 1)
        self.chkCam3 = QtGui.QCheckBox(self.groupBox)
        self.chkCam3.setText(_fromUtf8(""))
        self.chkCam3.setObjectName(_fromUtf8("chkCam3"))
        self.gridLayout.addWidget(self.chkCam3, 2, 0, 1, 1)
        self.pbRecord2 = QtGui.QPushButton(self.groupBox)
        self.pbRecord2.setEnabled(False)
        self.pbRecord2.setCheckable(True)
        self.pbRecord2.setChecked(False)
        self.pbRecord2.setObjectName(_fromUtf8("pbRecord2"))
        self.gridLayout.addWidget(self.pbRecord2, 1, 3, 1, 1)
        self.txtDesc2 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc2.setFont(font)
        self.txtDesc2.setObjectName(_fromUtf8("txtDesc2"))
        self.gridLayout.addWidget(self.txtDesc2, 1, 2, 1, 1)
        self.pbCam3 = QtGui.QPushButton(self.groupBox)
        self.pbCam3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam3.sizePolicy().hasHeightForWidth())
        self.pbCam3.setSizePolicy(sizePolicy)
        self.pbCam3.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam3.setFont(font)
        self.pbCam3.setCheckable(True)
        self.pbCam3.setObjectName(_fromUtf8("pbCam3"))
        self.gridLayout.addWidget(self.pbCam3, 2, 1, 1, 1)
        self.txtDesc3 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc3.setFont(font)
        self.txtDesc3.setObjectName(_fromUtf8("txtDesc3"))
        self.gridLayout.addWidget(self.txtDesc3, 2, 2, 1, 1)
        self.chkCam4 = QtGui.QCheckBox(self.groupBox)
        self.chkCam4.setText(_fromUtf8(""))
        self.chkCam4.setObjectName(_fromUtf8("chkCam4"))
        self.gridLayout.addWidget(self.chkCam4, 3, 0, 1, 1)
        self.pbRecord3 = QtGui.QPushButton(self.groupBox)
        self.pbRecord3.setEnabled(False)
        self.pbRecord3.setCheckable(True)
        self.pbRecord3.setChecked(False)
        self.pbRecord3.setObjectName(_fromUtf8("pbRecord3"))
        self.gridLayout.addWidget(self.pbRecord3, 2, 3, 1, 1)
        self.pbCam4 = QtGui.QPushButton(self.groupBox)
        self.pbCam4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam4.sizePolicy().hasHeightForWidth())
        self.pbCam4.setSizePolicy(sizePolicy)
        self.pbCam4.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam4.setFont(font)
        self.pbCam4.setCheckable(True)
        self.pbCam4.setObjectName(_fromUtf8("pbCam4"))
        self.gridLayout.addWidget(self.pbCam4, 3, 1, 1, 1)
        self.pbRecord4 = QtGui.QPushButton(self.groupBox)
        self.pbRecord4.setEnabled(False)
        self.pbRecord4.setCheckable(True)
        self.pbRecord4.setChecked(False)
        self.pbRecord4.setObjectName(_fromUtf8("pbRecord4"))
        self.gridLayout.addWidget(self.pbRecord4, 3, 3, 1, 1)
        self.txtDesc4 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc4.setFont(font)
        self.txtDesc4.setObjectName(_fromUtf8("txtDesc4"))
        self.gridLayout.addWidget(self.txtDesc4, 3, 2, 1, 1)
        self.txtDesc5 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDesc5.setFont(font)
        self.txtDesc5.setObjectName(_fromUtf8("txtDesc5"))
        self.gridLayout.addWidget(self.txtDesc5, 4, 2, 1, 1)
        self.pbCam5 = QtGui.QPushButton(self.groupBox)
        self.pbCam5.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCam5.sizePolicy().hasHeightForWidth())
        self.pbCam5.setSizePolicy(sizePolicy)
        self.pbCam5.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbCam5.setFont(font)
        self.pbCam5.setCheckable(True)
        self.pbCam5.setObjectName(_fromUtf8("pbCam5"))
        self.gridLayout.addWidget(self.pbCam5, 4, 1, 1, 1)
        self.chkCam5 = QtGui.QCheckBox(self.groupBox)
        self.chkCam5.setText(_fromUtf8(""))
        self.chkCam5.setObjectName(_fromUtf8("chkCam5"))
        self.gridLayout.addWidget(self.chkCam5, 4, 0, 1, 1)
        self.pbRecord5 = QtGui.QPushButton(self.groupBox)
        self.pbRecord5.setEnabled(False)
        self.pbRecord5.setCheckable(True)
        self.pbRecord5.setChecked(False)
        self.pbRecord5.setObjectName(_fromUtf8("pbRecord5"))
        self.gridLayout.addWidget(self.pbRecord5, 4, 3, 1, 1)
        self.pbRotate4 = QtGui.QPushButton(self.groupBox)
        self.pbRotate4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRotate4.sizePolicy().hasHeightForWidth())
        self.pbRotate4.setSizePolicy(sizePolicy)
        self.pbRotate4.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pbRotate4.setCheckable(True)
        self.pbRotate4.setObjectName(_fromUtf8("pbRotate4"))
        self.gridLayout.addWidget(self.pbRotate4, 3, 4, 1, 1)
        self.pbRotate1 = QtGui.QPushButton(self.groupBox)
        self.pbRotate1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRotate1.sizePolicy().hasHeightForWidth())
        self.pbRotate1.setSizePolicy(sizePolicy)
        self.pbRotate1.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pbRotate1.setCheckable(True)
        self.pbRotate1.setObjectName(_fromUtf8("pbRotate1"))
        self.gridLayout.addWidget(self.pbRotate1, 0, 4, 1, 1)
        self.pbRotate2 = QtGui.QPushButton(self.groupBox)
        self.pbRotate2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRotate2.sizePolicy().hasHeightForWidth())
        self.pbRotate2.setSizePolicy(sizePolicy)
        self.pbRotate2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pbRotate2.setCheckable(True)
        self.pbRotate2.setObjectName(_fromUtf8("pbRotate2"))
        self.gridLayout.addWidget(self.pbRotate2, 1, 4, 1, 1)
        self.pbRotate3 = QtGui.QPushButton(self.groupBox)
        self.pbRotate3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRotate3.sizePolicy().hasHeightForWidth())
        self.pbRotate3.setSizePolicy(sizePolicy)
        self.pbRotate3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pbRotate3.setCheckable(True)
        self.pbRotate3.setObjectName(_fromUtf8("pbRotate3"))
        self.gridLayout.addWidget(self.pbRotate3, 2, 4, 1, 1)
        self.pbRotate5 = QtGui.QPushButton(self.groupBox)
        self.pbRotate5.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRotate5.sizePolicy().hasHeightForWidth())
        self.pbRotate5.setSizePolicy(sizePolicy)
        self.pbRotate5.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pbRotate5.setCheckable(True)
        self.pbRotate5.setObjectName(_fromUtf8("pbRotate5"))
        self.gridLayout.addWidget(self.pbRotate5, 4, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(CamDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CamDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CamDialog.close)
        QtCore.QObject.connect(self.chkCam1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam1.setEnabled)
        QtCore.QObject.connect(self.chkCam2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam2.setEnabled)
        QtCore.QObject.connect(self.chkCam3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam3.setEnabled)
        QtCore.QObject.connect(self.chkCam4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam4.setEnabled)
        QtCore.QObject.connect(self.chkCam5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbCam5.setEnabled)
        QtCore.QObject.connect(self.chkCam1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRecord1.setEnabled)
        QtCore.QObject.connect(self.chkCam2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRecord2.setEnabled)
        QtCore.QObject.connect(self.chkCam3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRecord3.setEnabled)
        QtCore.QObject.connect(self.chkCam4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRecord4.setEnabled)
        QtCore.QObject.connect(self.chkCam5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRecord5.setEnabled)
        QtCore.QObject.connect(self.chkCam1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRotate1.setEnabled)
        QtCore.QObject.connect(self.chkCam2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRotate2.setEnabled)
        QtCore.QObject.connect(self.chkCam3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRotate3.setEnabled)
        QtCore.QObject.connect(self.chkCam4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRotate4.setEnabled)
        QtCore.QObject.connect(self.chkCam5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbRotate5.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CamDialog)
        CamDialog.setTabOrder(self.chkCam1, self.pbCam1)
        CamDialog.setTabOrder(self.pbCam1, self.txtDesc1)
        CamDialog.setTabOrder(self.txtDesc1, self.pbRecord1)
        CamDialog.setTabOrder(self.pbRecord1, self.chkCam2)
        CamDialog.setTabOrder(self.chkCam2, self.pbCam2)
        CamDialog.setTabOrder(self.pbCam2, self.txtDesc2)
        CamDialog.setTabOrder(self.txtDesc2, self.pbRecord2)
        CamDialog.setTabOrder(self.pbRecord2, self.chkCam3)
        CamDialog.setTabOrder(self.chkCam3, self.pbCam3)
        CamDialog.setTabOrder(self.pbCam3, self.txtDesc3)
        CamDialog.setTabOrder(self.txtDesc3, self.pbRecord3)
        CamDialog.setTabOrder(self.pbRecord3, self.chkCam4)
        CamDialog.setTabOrder(self.chkCam4, self.pbCam4)
        CamDialog.setTabOrder(self.pbCam4, self.txtDesc4)
        CamDialog.setTabOrder(self.txtDesc4, self.pbRecord4)
        CamDialog.setTabOrder(self.pbRecord4, self.chkCam5)
        CamDialog.setTabOrder(self.chkCam5, self.pbCam5)
        CamDialog.setTabOrder(self.pbCam5, self.txtDesc5)
        CamDialog.setTabOrder(self.txtDesc5, self.pbRecord5)
        CamDialog.setTabOrder(self.pbRecord5, self.buttonBox)

    def retranslateUi(self, CamDialog):
        CamDialog.setWindowTitle(_translate("CamDialog", "SSM Cameras", None))
        self.groupBox.setTitle(_translate("CamDialog", "Cameras", None))
        self.txtDesc1.setText(_translate("CamDialog", "Description", None))
        self.pbRecord1.setText(_translate("CamDialog", "Record", None))
        self.pbCam1.setText(_translate("CamDialog", "1", None))
        self.pbCam2.setText(_translate("CamDialog", "2", None))
        self.pbRecord2.setText(_translate("CamDialog", "Record", None))
        self.txtDesc2.setText(_translate("CamDialog", "Description", None))
        self.pbCam3.setText(_translate("CamDialog", "3", None))
        self.txtDesc3.setText(_translate("CamDialog", "Description", None))
        self.pbRecord3.setText(_translate("CamDialog", "Record", None))
        self.pbCam4.setText(_translate("CamDialog", "4", None))
        self.pbRecord4.setText(_translate("CamDialog", "Record", None))
        self.txtDesc4.setText(_translate("CamDialog", "Description", None))
        self.txtDesc5.setText(_translate("CamDialog", "Description", None))
        self.pbCam5.setText(_translate("CamDialog", "5", None))
        self.pbRecord5.setText(_translate("CamDialog", "Record", None))
        self.pbRotate4.setText(_translate("CamDialog", "Rotate", None))
        self.pbRotate1.setText(_translate("CamDialog", "Rotate", None))
        self.pbRotate2.setText(_translate("CamDialog", "Rotate", None))
        self.pbRotate3.setText(_translate("CamDialog", "Rotate", None))
        self.pbRotate5.setText(_translate("CamDialog", "Rotate", None))

